apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patches:
# ServiceAccount - make name unique per environ 
- target:
    kind: Deployment
    name: frontend
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: gcr.io/dev-anthos-online-boutique/frontend@sha256:782cee10b929ad944cdc8b4c070d1a94c63c88b3591366443ae1115521df0e94
commonLabels:
  environment: dev
# [END anthosconfig_multi_environments_kustomize_config_source_overlays_dev_kustomization] 
