apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patches:
# ServiceAccount - make name unique per environ 
- target:
    kind: Deployment
    name: frontend
  patch: |-
    - op: replace
      path: /spec/template/spec/image
      value: gcr.io/dev-anthos-online-boutique/frontend@sha256:ae94bc75c60f6894bc8349a70fd303a472382e1601725719bf8222119a08cc75
commonLabels:
  environment: dev
# [END anthosconfig_multi_environments_kustomize_config_source_overlays_dev_kustomization] 
