apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend
      environment: dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      creationTimestamp: null
      labels:
        app: frontend
        environment: dev
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: productcatalogservice.product-catalog.svc.cluster.local:3550
        - name: CURRENCY_SERVICE_ADDR
          value: currencyservice.currency.svc.cluster.local:7000
        - name: CART_SERVICE_ADDR
          value: cartservice.cart.svc.cluster.local:7070
        - name: RECOMMENDATION_SERVICE_ADDR
          value: recommendationservice.recommendation.svc.cluster.local:8080
        - name: SHIPPING_SERVICE_ADDR
          value: shippingservice.shipping.svc.cluster.local:50051
        - name: CHECKOUT_SERVICE_ADDR
          value: checkoutservice.checkout.svc.cluster.local:5050
        - name: AD_SERVICE_ADDR
          value: adservice.ad.svc.cluster.local:9555
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        image: gcr.io/dev-anthos-online-boutique/frontend@sha256:39d62463c96de5bede2e9c71fde4847366c84a8e36b6a49f8d4eb39cf335585e
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Cookie
              value: shop_session-id=x-liveness-probe
            path: /_healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: server
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Cookie
              value: shop_session-id=x-readiness-probe
            path: /_healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: frontend
      serviceAccountName: frontend
      terminationGracePeriodSeconds: 30